### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#10]
```
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:565)
	at java.base/java.lang.Integer.parseInt(Integer.java:685)
	at org.eolang.lints.LintByXsl.defects(LintByXsl.java:94)
	at org.eolang.lints.Program.defects(Program.java:80)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.6`
