### ISSUE TITLE
Cannot convert string "41.29.301" to double

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#81]
```
Caused by: java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.jaxp.TransformerImpl: Cannot convert string "41.29.301" to double; SystemID: file:///Volumes/sec/code/o/eo/eo-maven-plugin/object-line-out-of-listing; Line#: 30; Column#: 28
	at com.jcabi.xml.XSLDocument.transformInto(XSLDocument.java:446)
	at com.jcabi.xml.XSLDocument.transform(XSLDocument.java:400)
	at org.eolang.lints.LintByXsl.defects(LintByXsl.java:98)
	at org.eolang.lints.Program.defects(Program.java:87)

```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.15`
